export const CARD_BG = [
    { id:1, bgcolor:'Linear-gradient(135deg,#e6f8f3 0%, #f7fcfa 100%)'},
    { id:2, bgcolor:'Linear-gradient(135deg,#fef9e7 0%, #fffdf4 100%)'},
    { id:3, bgcolor:'Linear-gradient(135deg,#eaf7ff 0%, #f3fbff 100%)'},
    { id:4, bgcolor:'Linear-gradient(135deg,#fff2e9 0%, #fff8f3 100%)'},
    { id:5, bgcolor:'Linear-gradient(135deg,#e7f6fe 0%, #f4fafd 100%)'},
    { id:6, bgcolor:'Linear-gradient(135deg,#f5f5f5 0%, #fbfbfb 100%)'},
    { id:7, bgcolor:'Linear-gradient(135deg,#fff4fc 0%, #fff8fd 100%)'},
    { id:8, bgcolor:'Linear-gradient(135deg,#e8fef3 0%, #f5fef8 100%)'},
    { id:9, bgcolor:'Linear-gradient(135deg,#f0ecff 0%, #f7f5ff 100%)'},
    { id:10, bgcolor:'Linear-gradient(135deg,#fef2f2 0%, #fff8f8 100%)'},
];

// export const APP_FEATURES = [
//     {
//         id: "01",
//         title: "Tailored Just for You",
//         description: "Get interview question and model answer based on your role , experience, and specific focus area.",
//     },
//     {
//         id: "02",
//         title: "Learn at Your Own Pace",
//         description: "expand answers, dive deeper into concepts, and explore related topics at your own pace.",
//     },
//     {
//         id: "03",
//         title: "Capture Your Insights",
//         description: "Add personal notes to any question and pin impoetant ones on the top - make your preparation organized and effective.",
//     },
//     {
//         id: "04",
//         title: 'Understand the "why" Behind Answers',
//         description: "Beyond just answers - unlock detailed concept explanations generated by AI to help you grasp the underlying principles.",
//     },
//     {
//         id: "05",
//         title: "Save, Organize, and Revisit",
//         description: "Easily save your interview sets, organize them neaatly in your database, and pick up preparation right where you left off.",
//     },
// ];

export const APP_FEATURES = [
    {
        id: "01",
        title: "Personalized for Your Journey",
        description: "Get interview questions and model answers tailored to your role, experience level, and areas of focus.",
    },
    {
        id: "02",
        title: "Learn on Your Terms",
        description: "Expand answers, explore deeper concepts, and study related topics at your own comfortable pace.",
    },
    {
        id: "03",
        title: "Stay Sharp, Pin Smart",
        description: "Quickly pin must-review questions to the top , so your high-priority content is always just a scroll away.",
    },
    {
        id: "04",
        title: "Master the 'Why'",
        description: "Don’t just memorize—understand. Get detailed AI-generated explanations that break down the reasoning behind each answer.",
    },
    {
        id: "05",
        title: "Save, Sort & Come Back Anytime",
        description: "Save your interview sets, organize them seamlessly, and resume your prep exactly where you left off.",
    },
];
